export default {
  paylater: require('./paylater.png'),
  other: require('./other.png'),
  pay: require('./pay.png'),
  topup: require('./topup.png'),
  gocar: require('./gocar.png'),
  gofood: require('./gofood.png'),
  gomart: require('./gomart.png'),
  gomed: require('./gomed.png'),
  goride: require('./goride.png'),
  gosend: require('./gosend.png'),
  goshop: require('./goshop.png'),
  otherServices: require('./otherServices.png'),
  placeholder: require('./placeholder.png'),
  newsGofood: require('./covid-news.png'),
  newsCovid: require('./gofood-news.png'),
  menuHome: require('./menu-home.png'),
  menuOrders: require('./menu-orders.png'),
  menuChat: require('./menu-chat.png'),
  menuAccount: require('./menu-account.png'),
  menuInbox: require('./menu-inbox.png'),
  promo: require('./promo.png'),
};
